### ISSUE TITLE
unblur_tbz index errors

### ISSUE THREAD

**Issue by darthweider** [KryoEM/relion2#15]
I'm getting some index errors from unblur_tbz. I suspect it's because I'm not following the naming conventions that the code is expecting.

I ran:
```
cd /shared/process/guot/bgal_runthrough/
mpirun -n 4 sourced.sh
```
which calls unblur_tbz.py with the input tbz.star

At first, I had this error:
```
Traceback (most recent call last):
  File "/shared/relion/Relion2.0/relion2.0.2_custom/python//unblur_tbz.py", line 308, in <module>
    dose_per_frame, vol, pre_exp, first_frame, last_frame)
  File "/shared/relion/Relion2.0/relion2.0.2_custom/python//unblur_tbz.py", line 242, in main_mpi
    partial(mpi_finish,dstdir,do_aligned_movies))     
  File "/mnt/shared/relion/Relion2.0/relion2.0.2_custom/python/myutils/mpi.py", line 64, in scatter_list
    tasks          = init_fun()
  File "/shared/relion/Relion2.0/relion2.0.2_custom/python//unblur_tbz.py", line 193, in mpi_init
    tbzs      = star.getlist(starfile,key)    
  File "/mnt/shared/relion/Relion2.0/relion2.0.2_custom/python/myutils/star.py", line 15, in getlist
    idx = [i for i, x in enumerate(tf) if x][0]
IndexError: list index out of range
```

I think it was because I didn't name the star field correctly --
I had `_rlnTbzName` when it seems unblur_tbz was expecting `_rlnMicrographMovieName`.

Now I'm getting this error:
```
Traceback (most recent call last):
  File "/shared/relion/Relion2.0/relion2.0.2_custom/python//unblur_tbz.py", line 308, in <module>
    dose_per_frame, vol, pre_exp, first_frame, last_frame)
  File "/shared/relion/Relion2.0/relion2.0.2_custom/python//unblur_tbz.py", line 242, in main_mpi
    partial(mpi_finish,dstdir,do_aligned_movies))     
  File "/mnt/shared/relion/Relion2.0/relion2.0.2_custom/python/myutils/mpi.py", line 78, in scatter_list
    if __worker_iter(run_fun,comm,status) == TAGS.EXIT: 
  File "/mnt/shared/relion/Relion2.0/relion2.0.2_custom/python/myutils/mpi.py", line 25, in __worker_iter
    run_fun(task)
  File "/shared/relion/Relion2.0/relion2.0.2_custom/python//unblur_tbz.py", line 211, in mpi_run
    extract_tbz(tbz,nth)            
  File "/shared/relion/Relion2.0/relion2.0.2_custom/python//unblur_tbz.py", line 110, in extract_tbz
    tbz2mrc(srcdir,dsttbz,MOVSUFF,nthreads=nth)    
  File "/shared/relion/Relion2.0/relion2.0.2_custom/python//unblur_tbz.py", line 76, in tbz2mrc
    gainmrc = gain2mrc(srcdir)    
  File "/shared/relion/Relion2.0/relion2.0.2_custom/python//unblur_tbz.py", line 42, in gain2mrc
    gaindm4  = glob.glob(path)[0] 
IndexError: list index out of range
```

**Comment by kuybeda** [comment]
Yes, indeed I assumed a fixed fieldname in the star file. We shall make sure that our scripts that generate star files use the fixed field name.

Regarding the second error, it is because the source tbz folder /shared/data/betagal_raw/ does not contain gain calibration file. You probably forgot to copy it. It has .dm4 extension and "Gain" in its name. 

I will add some error checks and make these errors better reported.

**Comment by kuybeda** [comment]
Just copied the file and now testing.
